--
-- PostgreSQL database dump
--

\restrict 2ufvuEWgvF0MAUbj558Qx21aajBUjhR7YtDrdRgt45I4rWWlePCCMEAK3ccn6TC

-- Dumped from database version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: chat_histories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_histories (
    id bigint NOT NULL,
    assistant_response text NOT NULL,
    context_chunks jsonb,
    created_at timestamp(6) without time zone NOT NULL,
    response_time_ms bigint,
    session_id character varying(255) NOT NULL,
    token_usage jsonb,
    user_message text NOT NULL,
    knowledge_base_id bigint,
    user_id bigint NOT NULL
);


--
-- Name: chat_histories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_histories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document_chunks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_chunks (
    id bigint NOT NULL,
    chunk_position integer NOT NULL,
    content text NOT NULL,
    content_hash character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    embedding public.vector(1024),
    metadata jsonb,
    token_count integer,
    document_id bigint NOT NULL,
    knowledge_base_id bigint NOT NULL
);


--
-- Name: document_chunks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.document_chunks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_chunks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documents (
    id bigint NOT NULL,
    chunk_count integer,
    created_at timestamp(6) without time zone NOT NULL,
    file_hash character varying(255),
    file_path character varying(255) NOT NULL,
    file_size bigint,
    filename character varying(255) NOT NULL,
    mime_type character varying(255),
    original_filename character varying(255) NOT NULL,
    process_message character varying(1000),
    process_status character varying(255) NOT NULL,
    processed_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    knowledge_base_id bigint NOT NULL,
    CONSTRAINT documents_process_status_check CHECK (((process_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: knowledge_bases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.knowledge_bases (
    id bigint NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(500),
    name character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


--
-- Name: knowledge_bases_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.knowledge_bases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.knowledge_bases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    is_account_non_expired boolean NOT NULL,
    is_account_non_locked boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_credentials_non_expired boolean NOT NULL,
    email character varying(255) NOT NULL,
    is_enabled boolean NOT NULL,
    full_name character varying(255),
    last_login_at timestamp(6) without time zone,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    username character varying(50) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_histories chat_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_histories
    ADD CONSTRAINT chat_histories_pkey PRIMARY KEY (id);


--
-- Name: document_chunks document_chunks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_chunks
    ADD CONSTRAINT document_chunks_pkey PRIMARY KEY (id);


--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);


--
-- Name: knowledge_bases knowledge_bases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_bases
    ADD CONSTRAINT knowledge_bases_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_chat_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_created_at ON public.chat_histories USING btree (created_at);


--
-- Name: idx_chat_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_session_id ON public.chat_histories USING btree (session_id);


--
-- Name: idx_chat_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_user_id ON public.chat_histories USING btree (user_id);


--
-- Name: idx_chunk_doc_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chunk_doc_id ON public.document_chunks USING btree (document_id);


--
-- Name: idx_chunk_position; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chunk_position ON public.document_chunks USING btree (chunk_position);


--
-- Name: idx_doc_filename; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_doc_filename ON public.documents USING btree (filename);


--
-- Name: idx_doc_kb_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_doc_kb_id ON public.documents USING btree (knowledge_base_id);


--
-- Name: idx_kb_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kb_name ON public.knowledge_bases USING btree (name);


--
-- Name: idx_kb_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kb_user_id ON public.knowledge_bases USING btree (user_id);


--
-- Name: idx_user_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_email ON public.users USING btree (email);


--
-- Name: idx_user_username; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_username ON public.users USING btree (username);


--
-- Name: knowledge_bases fk2py2gvfth0eq9l8fdb96989bu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_bases
    ADD CONSTRAINT fk2py2gvfth0eq9l8fdb96989bu FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: chat_histories fk6n7xjf9q7mpe1dnxgbvswt1hv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_histories
    ADD CONSTRAINT fk6n7xjf9q7mpe1dnxgbvswt1hv FOREIGN KEY (knowledge_base_id) REFERENCES public.knowledge_bases(id);


--
-- Name: document_chunks fk_chunk_knowledge_base; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_chunks
    ADD CONSTRAINT fk_chunk_knowledge_base FOREIGN KEY (knowledge_base_id) REFERENCES public.knowledge_bases(id);


--
-- Name: chat_histories fkf6os2pmlidlgm6qdtxhkgc22o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_histories
    ADD CONSTRAINT fkf6os2pmlidlgm6qdtxhkgc22o FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: documents fkg0b5l2pgmqlpad1fbm49nwvb9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fkg0b5l2pgmqlpad1fbm49nwvb9 FOREIGN KEY (knowledge_base_id) REFERENCES public.knowledge_bases(id);


--
-- Name: document_chunks fkks8knsiau23lcmv9mydqjmj84; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_chunks
    ADD CONSTRAINT fkks8knsiau23lcmv9mydqjmj84 FOREIGN KEY (document_id) REFERENCES public.documents(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 2ufvuEWgvF0MAUbj558Qx21aajBUjhR7YtDrdRgt45I4rWWlePCCMEAK3ccn6TC

